:set ts=4
:set autoindent
:syntax on
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set softtabstop=4
:set nocompatible
:set number
:set ruler
:set confirm
:set formatoptions=crt
:set wildmenu
:set wildignore=*.o,*~,*.pyc
:set cmdheight=2
:set ignorecase
:set hlsearch
